---
pipelines:
  network_prod:
    group: "netmon"
    materials:
      netmon_scripts:
        type: git
        url: "https://github.com/devendrav1987/dev_netmon.git"
        branch: "main"
    timer:
      spec: "0 */10 * * * ? *"
    stages:
      - run_network_monitoring_whitelisting:
          script:
            - echo "Running network monitoring and whitelisting"
          when: on_success
          clean_workspace: true
          environment_variables:
            run_mode: prod
          jobs:
            run_update_script:
              timeout: 3
              resources:
                - git
                - python39
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-c"
                      - |
                        rm -rf ./netmon/ &&
                        python3 -m venv --without-pip netmon &&
                        cd netmon &&
                        source ./bin/activate &&
                        wget https://bootstrap.pypa.io/get-pip.py &&
                        python3 get-pip.py &&
                        ./bin/pip install netmiko &&
                        deactivate &&
                        cd .. &&
                        rm -rf ./dist/* &&
                        ./netmon/bin/python main_dv.py
