pipelines:
  network_prod:
    group: netmon
    materials:
      netmon_scripts:
        type: git
        url: https://github.com/devendrav1987/dev_netmon.git
        branch: main
    timer:
      spec: "0 */10 * * * ?"  # Removed the trailing `*` (invalid cron syntax)
    stages:
      - run_network_monitoring_whitelisting:
          jobs:
            run_update_script:
              timeout: 30  # Increased timeout (minutes)
              resources:
                - git
                - python39
              environment_variables:  # Moved here (job level)
                RUN_MODE: prod
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-c"
                      - |
                        rm -rf ./netmon/
                        python3 -m venv netmon
                        source ./netmon/bin/activate
                        pip install netmiko
                        python main_dv.py
                        deactivate
